### PR TITLE
adding CFPrefs state and making profile modules stateful

### PR DESCRIPTION
**Pull request by weswhet**
Makes profile module stateful

new CFPrefs state.

### CODE REVIEW

**Comment by twangboy** [comment]
Could these be put in the develop branch in salt?

**Review by twangboy — APPROVED** [review]

**Comment by weswhet** [comment]
@twangboy that's the plan. Especially since salt will ship with pyobjc :). I just put them up here to get extra eyes on it before filing the PR into the main project.

**Comment by twangboy** [comment]
You're going to revolutionize the way modules are written for OS X...

**Comment by twangboy** [comment]
Sorry, I just realized this is your own repo... not ours... Do what you will

**Comment by mosen** [comment]
Wes, you’re taking credit on my repo that’s no fair 😛

**Comment by weswhet** [comment]
I’m going to build a monument in your honor mosen. Everyone knows you’re the OG mac salt godfather.

**Comment by sheagcraig** [comment]
Yo @twangboy. Working on prettifying it for inclusion to develop.

**Pull request merged**
